### ISSUE TITLE
Feature Request: License Information

### ISSUE THREAD

**Issue by brianjahnke** [International-Data-Spaces-Association/Java-Representation-of-IDS-Information-Model#4]
Please include license information in the build artifacts so that e.g. maven can query those automatically.
At the moment the license will be returned as 'Unknown', which makes it harder to verify dependency's licenses automated.

**Comment by maboeckmann** [comment]
Hi,
I have recently added the license not only as part of the artifact but also to the POM. Maven should now recognize it. Could you please test again?

**Comment by brianjahnke** [comment]
Hi,
worked like a charm! Thx!

![grafik](https://user-images.githubusercontent.com/74709618/123085356-6dbcd300-d422-11eb-9786-8bb847307c50.png)
